# -*- coding: utf-8 -*-
"""Decision tree using XGboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQSXx6V1cMZAwMbKFEPlayCqVz-HuJQ2
"""

import xgboost as xgb
from sklearn.metrics import accuracy_score

# Sample dataset
data = {
    'FeatureA': [2, 1, 3, 2],
    'FeatureB': [3, 4, 2, 1],
    'Label': [0, 0, 1, 1]
}
df = pd.DataFrame(data)
X = df[['FeatureA', 'FeatureB']]
y = df['Label']

# Train an XGBoost classifier
model = xgb.XGBClassifier(criterion='entropy', use_label_encoder=False)
model.fit(X, y)

# Predict
predictions = model.predict(X)
print("Predictions:", predictions)
print("Accuracy:", accuracy_score(y, predictions))