# -*- coding: utf-8 -*-
"""Random Forest Classifier and Regressor Sklearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbRN2QhQlzl7oNkxJ-zCwMot3o5bxTQP
"""

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error

# Sample data for classification
X_classification = [[1, 2], [3, 4], [5, 6], [7, 8]]
y_classification = [0, 1, 0, 1]

# Create and train the classifier
clf = RandomForestClassifier(n_estimators=100, max_features='sqrt', random_state=42)
clf.fit(X_classification, y_classification)

# Make predictions
predictions_class = clf.predict([[2, 3], [6, 7]])
print(f"Classification Predictions: {predictions_class}")

# Sample data for regression
X_regression = [[1, 2], [3, 4], [5, 6], [7, 8]]
y_regression = [10, 20, 30, 40]

# Create and train the regressor
reg = RandomForestRegressor(n_estimators=100, max_features='sqrt', random_state=42)
reg.fit(X_regression, y_regression)

# Make predictions
predictions_reg = reg.predict([[2, 3], [6, 7]])
print(f"Regression Predictions: {predictions_reg}")